### PR TITLE
Masterserver DNS change

### PR DESCRIPTION
**Pull request by jeefo**
.su domain zone isn't cheap enough, if anyone want to continue to use it and have webnames account i will be happy to transfer it.

happily .ru zone is cheap, and fwgs.ru was free, so i've registered it. so masterserver dns change is a must, if no one will support xash.su zone

@a1batross i have granted you access to fwgs.ru zone @cloudns.

### CODE REVIEW

**Comment by mittorn** [comment]
It will kill multiplayer. Maybe we need to set up new domain zone, but keep old running some time.
Or keep it running until protocol change (it will be changed after UnkleMike's update, but we don't know when it will be released)

**Comment by jeefo** [comment]
Zone paid till 02/18. So we have almost a year.

**Comment by a1batross** [comment]
Well, I can take the ownership of xash.su, so it's not a serious trouble.

**Comment by a1batross** [comment]
Seems to be resolved without changing domain address? I think we still need hardcode a backup addresses for master server and provide a configuration file(like MasterServers.vdf).

**Pull request closed without merging**
