### PR TITLE
blood drips scale and direction fix

### PR DESCRIPTION
**Pull request by porloc**
Blood drips shows amount of damage done to the enemy. Drips currently too small to see them and flew up instead of flying to side and falling down like in goldsrc engine. Fixed scale and flight direction of blood drips to look like in goldsrc engine.

### CODE REVIEW

**Comment by porloc** [comment]
Yeah, your suggestion is more correct. I made blood drops too big.

**Comment by a1batross** [comment]
I tested it. It's completely wrong now.

**Comment by a1batross** [comment]
I have re-visited them, so now they look almost like GoldSrc(except gamma). 

Look in 5016b38667e49b762775d4ef3e498ae7695d54d8.

**Comment by a1batross** [comment]
@porloc drips were spawned at player head, also low drip spread.

Source SDK have marked this effect as legacy and deprecated. They are not intended to work and look now.

**Comment by a1batross** [comment]
Yes, it should be built automatically and posted to xash3d-deploy repo.

**Pull request closed without merging**
