### PR TITLE
Add sv_simulating cvar

### PR DESCRIPTION
**Pull request by THE-Swank**

### CODE REVIEW

**Comment by a1batross** [comment]
So... this basically for forcing simulating when server don't have active players? Why it's on start of function? 

Also, the cvar name and description is seem to be unclear. What does mean by "mode"? How user must know that cvar value 2 will force simulating? 0 is useless at all, because there is "playersonly" command exist. I also think that switching simulating rules is a cheat(sort of).

**Comment by THE-Swank** [comment]
Да, это в первую очередь для принудительной симоляции на пустом сервере.
sv_forcesimulating, 1 - симуляция всегда, 0 - обычная модель симуляции, так лучше?

**Comment by a1batross** [comment]
Da.

28 нояб. 2016 г. 1:55 AM пользователь "THE-Swank" <notifications@github.com>
написал:

**Comment by a1batross** [comment]
Блин, я промахнулся.

**Pull request merged**
